apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    kubernetes.io/ingress.class: "{{ ingress_class }}"
    cert-manager.io/cluster-issuer: "{{ ingress_issuer }}"
  name: yopass-ingress
  namespace: personal-utils
spec:
  rules:
  - host: {{ yopass_ingress_domain }}
    http:
      paths:
      - backend:
          serviceName: yopass-yopass-http
          servicePort: 80
        path: /
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - {{ yopass_ingress_domain }}
    secretName: {{ yopass_ingress_domain }}-tls # < cert-manager will store the created certificate in this secret.
