apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: yopass-ingress
  namespace: personal-utils
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ yopass_ingress_domain }}`)
      kind: Rule
      services:
      - name: yopass-yopass-http
        port: 80
      middlewares:
        - name: kube-system-security@kubernetescrd
  tls: {}
