---
- name: Copy over deploy file
  template:
    src: "{{ item }}"
    dest: "{{ temp_dir }}/{{ item }}"
  with_items:
    - apt-cacher-deployment.yaml

- name: Create cache-services namespace
  k8s:
    name: cache-services
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: Namespace
    state: present

- name: Apply deployment file
  k8s:
    state: present
    namespace: drone
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ temp_dir }}/{{ item }}"
  with_items:
    - apt-cacher-deployment.yaml
