---
- name: Copy over deploy file
  template:
    src: "{{ item }}"
    dest: "{{ temp_dir }}/{{ item }}"
  with_items:
    - drone-secrets.yaml
    - drone-ingress.yaml
    - drone-helm.yaml

- name: Create drone namespace
  k8s:
    name: drone
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: Namespace
    state: present

- name: Import secret
  k8s:
    state: present
    namespace: drone
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ temp_dir }}/drone-secrets.yaml"

- name: Remove secret file
  file:
    path: "{{ temp_dir }}/drone-secrets.yaml"
    state: absent

- name: Install drone from helm
  k8s:
    state: present
    namespace: drone
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ temp_dir }}/{{ item }}"
  with_items:
    - drone-helm.yaml
    - drone-ingress.yaml
