apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: drone
  namespace: drone
spec:
  repo: {{ drone_chart_url }}
  chart: drone
  set:
    image.tag: "{{ drone_image_tag }}"
    persistentVolume.storageClass: "nfs-client"
    extraSecretNamesForEnvFrom[0]: drone-gitea-secret
    env.DRONE_SERVER_HOST: "{{ drone_ingress_domain }}"
    env.DRONE_SERVER_PROTO: https
    env.DRONE_GIT_ALWAYS_AUTH: "true"
    env.DRONE_GITEA_CLIENT_ID: "{{ drone_oauth_client_id }}"
    env.DRONE_GITEA_SERVER: "https://{{ gitea_ingress_domain }}"
    env.DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
