---
apiVersion: v1
kind: Secret
metadata:
  name: drone-gitea-secret
data:
  DRONE_GITEA_CLIENT_SECRET: "{{ drone_oauth_client_secret | string | b64encode }}"
  DRONE_RPC_SECRET: "{{ drone_rpc_secret | string | b64encode }}"
