apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chronograf-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ chronograf_ingress_domain }}`)
      kind: Rule
      services:
      - name: chronograf-chronograf
        port: 80
      middlewares:
        - name: kube-system-traefik-sso@kubernetescrd
  tls: {}
