apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: chronograf
  namespace: monitoring
spec:
  chart: chronograf
  repo: {{ influxdata_chart_url }}
  set:
    image.repository: chronograf
    image.tag: {{ chronograf_image_tag }}
    persistence.enabled: "true"
    persistence.storageClass: "nfs-client"
