apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: telegraf-ds
  namespace: monitoring
spec:
  chart: telegraf-ds
  repo: {{ influxdata_chart_url }}
  set:
    image.tag: {{ telegraf_ds_image_tag }}
  valuesContent: |-
    config:
      outputs:
      - influxdb:
          urls:
            - "http://influxdb:8086"
          database: "telegraf"
