# Section: unifi-poller deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: unifi-poller
  labels:
    app: unifi-poller
    component: unifi-poller
spec:
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: unifi-poller
  replicas: 1
  template:
    metadata:
      name: unifi-poller
      labels:
        app: unifi-poller
        component: unifi-poller
    spec:
      containers:
      - name: unifi-poller
        image: {{ unifi_poller_image }}
        env:
          - name: UP_UNIFI_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: unifi-secret
                key: username
          - name: UP_UNIFI_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: unifi-secret
                key: password
          - name: UP_INFLUXDB_DB
            value: "unifi"
          - name: UP_INFLUXDB_DB
            value: "unifi"
          - name: UP_INFLUXDB_URL
            value: "http://influxdb:8086"
          - name: UP_UNIFI_DEFAULT_URL
            value: "https://192.168.1.9:8443"
          - name: UP_UNIFI_DEFAULT_SAVE_DPI
            value: "{{ unifi_dpi_enabled }}"
